TILE_COLOR = "chartreuse"
TILE_SIZE = 256
TILE_BORDER_SIZE = 0
TILE_BORDER_COLOR = "#FFAB40"

MAP_TILE_BORDER_SIZE = 3
MAP_TILE_BORDER_PADDING = 6
MAP_TILE_AREA_PADDING = 4

GRID_ROWS = 16
GRID_COLUMNS = 16

SCALE_FACTOR = 1

CURRENT_VERSION = 'v0.2.2'